language: csharp
solution: AsyncSockets.sln
matrix:
  install:
      - nuget restore ./AsyncSockets/AsyncSockets.sln
  include:
    - mono: latest
      script:
        - xbuild /p:Configuration=Release ./AsyncSockets/AsyncSockets.sln
  