language: csharp
solution: AsyncSockets.sln
install:
  - nuget restore ./AsyncSockets/AsyncSockets.sln
matrix:
  include:
    - mono: latest
      script:
        - xbuild /p:Configuration=Release ./AsyncSockets/AsyncSockets.sln
  